spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  profiles:
    include: oauth,real-db
  session:
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION

server:
  servlet:
    encoding:
      force-response: true